# Generated by Django 3.1.12 on 2021-12-12 23:47

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLog',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('achivement', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=20)),
                ('tag_jobdam', models.CharField(max_length=20)),
                ('tag_pilgi', models.CharField(max_length=20)),
                ('tag_jindo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True)),
                ('lecture_id', models.CharField(blank=True, max_length=30)),
                ('lecture_title', models.CharField(blank=True, max_length=30)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('achivement', models.CharField(max_length=20)),
                ('tag_jobdam', models.CharField(max_length=20)),
                ('tag_pilgi', models.CharField(max_length=20)),
                ('tag_jindo', models.CharField(max_length=20)),
                ('lec_comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
